version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
volumes:
  mysql_data:
